### ISSUE TITLE
请问支持多线程上传吗？

### ISSUE THREAD

**Issue by JIA-Jimmy** [FortuneDayssss/BilibiliUploader#1]
客户端同时支持上传5个视频，BilibiliUploader可否支持同时上传多个分段，还是直接调chunk大小来提高上传速度？

**Comment by FortuneDayssss** [comment]
目前不支持多线程上传，我之后有时间的话会把多线程上传功能加进去

**Comment by FortuneDayssss** [comment]
如果你指的是上传单个视频文件切分的chunk的话，chunk大小是B站API固定的不能更改

**Comment by JIA-Jimmy** [comment]
> 如果你指的是上传单个视频文件切分的chunk的话，chunk大小是B站API固定的不能更改

好的，谢谢大佬告知

**Comment by FortuneDayssss** [comment]
[#0.0.2](https://github.com/FortuneDayssss/BilibiliUploader/releases/tag/0.0.2)
多线程上传功能新版本已经实现

**Comment by JIA-Jimmy** [comment]
> [#0.0.2](https://github.com/FortuneDayssss/BilibiliUploader/releases/tag/0.0.2)
> 多线程上传功能新版本已经实现

大佬牛逼！用上了
