### ISSUE TITLE
--

### ISSUE THREAD

**Issue by RiotGamesU** [FortuneDayssss/BilibiliUploader#13]

**Comment by FortuneDayssss** [comment]
这个repo没有录制的功能，想又录直播又发b站选StreamHelper。
只想发b站投稿的话熟悉python用这个，熟悉js用那个。

**Comment by RiotGamesU** [comment]
> 这个repo没有录制的功能，想又录直播又发b站选StreamHelper。
> 只想发b站投稿的话熟悉python用这个，熟悉js用那个。

好的 谢谢大佬 请问
https://github.com/ZhangMingZhao1/StreamerHelper
和
https://github.com/ForgQi/bilibiliupload
这俩有啥区别呀 不考虑操作系统的前提下 用哪个比较好呢
