### ISSUE TITLE
No module named 'bilibiliuploader'? pip install 也报错

### ISSUE THREAD

**Issue by zehaoj** [FortuneDayssss/BilibiliUploader#15]
可以教一下怎么安装这个包嘛？直接pip install bilibiliuploader会报错，Ubuntu 18.04，谢谢！

**Comment by FortuneDayssss** [comment]
我没有上传到pypi所以没法直接pip安装，可以按照下面这样安装
pip3 install https://github.com/FortuneDayssss/BilibiliUploader/releases/download/0.0.4/bilibiliuploader-0.0.4.tar.gz
