### ISSUE TITLE
请问这个是什么原因啊？

### ISSUE THREAD

**Issue by aqlkzf** [FortuneDayssss/BilibiliUploader#17]
Traceback (most recent call last):
  File "D:/chromedown/bilibiliuploader-0.0.4/bilibiliuploader-0.0.4/test.py", line 43, in <module>
    thread_pool_workers=5,
  File "D:\chromedown\bilibiliuploader-0.0.4\bilibiliuploader-0.0.4\bilibiliuploader\bilibiliuploader.py", line 71, in upload
    thread_pool_workers)
  File "D:\chromedown\bilibiliuploader-0.0.4\bilibiliuploader-0.0.4\bilibiliuploader\core.py", line 504, in upload
    status = status and t_obj.result()
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chromedown\bilibiliuploader-0.0.4\bilibiliuploader-0.0.4\bilibiliuploader\core.py", line 400, in upload_video_part
    pre_upload_data = r.json()
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by FortuneDayssss** [comment]
返回的内容不是json导致错误。。。
盲猜是网络环境的问题....

**Comment by aqlkzf** [comment]
![image](https://user-images.githubusercontent.com/67051837/116839018-37718d00-ac03-11eb-8940-84350bf1ffdd.png)
还是这个错误，请问巨佬这个脚本您那边现在还可以正常使用吗？  我一直报错。。。

**Comment by FortuneDayssss** [comment]
我这边有个项目用这个包稳定跑了一年多了一直没出过任何问题.......所以我不太认为是代码里出错了

也许你是的json包版本有问题？你试一试把anaconda换成pip还会不会出现这个问题，如果还会的话我们继续具体分析一下原因吧。
我这边看这个报错其实不太能看出代码里的问题....

**Comment by aqlkzf** [comment]
您好，请问您那边使用的python版本是什么？ 或许是我这个为了跑深度学习安装的python版本较低的原因

**Comment by FortuneDayssss** [comment]
在我的生产环境里用的python3.6.9，3.6.9跑了一年多了没出过任何问题。我认为>=3.6.9版本出问题的概率不大。你也许可以用高版本python试试

**Comment by aqlkzf** [comment]
![image](https://user-images.githubusercontent.com/67051837/116841031-7525e400-ac0a-11eb-9926-4abc52ff15ec.png)
巨佬您好，原来是我登录报错了，我选择的是用户名+密码登录，请问这个要怎么修改？ 选择其他方式登录吗？ 本人小白，感谢巨佬不吝赐教

**Comment by FortuneDayssss** [comment]
-629代码是“用户名或密码错误”。你看下你使用的（用户名+密码）是否拼写正确？

**Comment by aqlkzf** [comment]
![image](https://user-images.githubusercontent.com/67051837/116841910-347b9a00-ac0d-11eb-8594-c9b2298796b3.png)
wo'g'g我刚刚手动登录试过了，这个是不是需要短信验证码的原因？
请问access taken 是指的微信的那个吗？

**Comment by aqlkzf** [comment]
请问可以直接使用cookie登录吗？

**Comment by FortuneDayssss** [comment]
Access token不是微信相关，而是使用用户名密码登录成功之后才能获取到的

因为是模拟的投稿工具，并不能用cookie登录

你可以试试用一个其他账号测试下是否能正常登录

**Comment by aqlkzf** [comment]
谢谢巨佬 我再试试

**Comment by aqlkzf** [comment]
![image](https://user-images.githubusercontent.com/67051837/117327977-c01f5000-aec5-11eb-9e24-32a04325e101.png)
![image](https://user-images.githubusercontent.com/67051837/117328021-cca3a880-aec5-11eb-85f9-1cc9400255fd.png)
再请问下巨佬，access_token 可以怎么获取啊，我用户名密码登录一直返回错误码-2100

**Comment by FortuneDayssss** [comment]
access_token是投稿工具输入账号密码成功登录之后服务器生成的一个随机数。只有成功登录之后才可以用。

你可以先试试用官方投稿工具软件能不能登录你这个账号。如果用官方软件可以成功登录的话那就应该是我这里的代码问题。你可以试试吗然后反馈一下谢谢。

**Comment by aqlkzf** [comment]
可以正常登录官方的投稿工具，不过需要输入短信验证码验证身份

**Comment by dfaofeng** [comment]
> 可以正常登录官方的投稿工具，不过需要输入短信验证码验证身份

登录成功后才可以获取access_token的 不跟短语验证相关

**Comment by FortuneDayssss** [comment]
> 可以正常登录官方的投稿工具，不过需要输入短信验证码验证身份

你可以用官方客户端登录，用fiddler抓包，然后把抓出的access token用于这个里面

**Comment by qazwsdc** [comment]
亲测，用户名密码登录的方式失效了，从昨天下午开始

**Comment by wpcwzy** [comment]
> 亲测，用户名密码登录的方式失效了，从昨天下午开始

@qazwsdc 反对一波，今天上午才用这个库成功上传了两稿多p视频（BV1BP4y1s727和BV1zf4y137dD）
考虑开issue上传一下失败log再分析一下？

**Comment by xiaoxinhuozhu** [comment]
> > 亲，用户名密码登录的方式失效了，从昨天开始
> 
> @qazwsdc反对一波，今天上午才用这个库成功上传了两稿多p视频（BV1BP4y1s727和BV1zf4y137dD）
> 考虑开题上传一次失败日志再分析一下？

我最近同样出现楼主的问题，配置都正确，但是突然有次-449错误，当时没放在心上。结果后面开始出现楼主问题，我怀疑是ip上传过多“被风控”，现在就是一会好一会坏，完全看运气。不知道这个是否支持代理上传，尝试下

**Comment by xiaoxinhuozhu** [comment]
> > 可以正常登录官方的投稿工具，不过需要输入短信验证码验证身份
> 
> 你可以用官方客户端登录，用fiddler抓包，然后把抓出的access token用于这个里面

最近又开始报错了，一会好一会坏是什么原因......

**Comment by wpcwzy** [comment]
> > > 亲测，用户名密码登录的方式失效了，从昨天开始
> > 
> > 
> > @qazwsdc反对一波，今天上午才用这个库成功上传了两稿多p视频（BV1BP4y1s727和BV1zf4y137dD）
> > 考虑开题上传一次失败日志再分析一下？
> 
> 我最近同样出现楼主的问题，配置都正确，但是突然有次-449错误，当时没放在心上。结果后面开始出现楼主问题，我怀疑是ip上传过多“被风控”，现在就是一会好一会坏，完全看运气。不知道这个是否支持代理上传，尝试下

-449理论上已经被 #24 修复了，看commit内容应该是哔哩哔哩日常api升级引起的。尝试用最新的release了吗？风控的话可以尝试登录官方投稿工具试一下，如果需要短信那就确实要用token登录了

**Comment by xiaoxinhuozhu** [comment]
> > > > 亲测，用户名密码登录的方式失效了，从昨天开始
> > > 
> > > 
> > > @qazwsdc反对一波，今天上午才用这个库成功上传了两稿多p视频（BV1BP4y1s727和BV1zf4y137dD）
> > > 考虑开题上传一次失败日志再分析一下？
> > 
> > 
> > 我最近同样出现楼主的问题，配置都正确，但是突然有次-449错误，当时没放在心上。结果后面开始出现楼主问题，我怀疑是ip上传过多“被风控”，现在就是一会好一会坏，完全看运气。不知道这个是否支持代理上传，尝试下
> 
> -449理论上已经被 #24 修复了，看commit内容应该是哔哩哔哩日常api升级引起的。尝试用最新的release了吗？风控的话可以尝试登录官方投稿工具试一下，如果需要短信那就确实要用token登录了

是的，我记得刚开始就是出现-449错误，我也修改了。但是用了半个月左右就开始出现-2100，是用最新的，官方投稿工具也完全不需要短信。我的意思不是账号“被风控”，而是ip的原因
当时我记得是布置了多个计划任务上传正常的，再我额外加了一个任务之后开始全部出现问题

**Comment by FortuneDayssss** [comment]
> > > > > 亲测，用户名密码登录的方式失效了，从昨天开始
> 
> > > > 
> 
> > > > 
> 
> > > > @qazwsdc反对一波，今天上午才用这个库成功上传了两稿多p视频（BV1BP4y1s727和BV1zf4y137dD）
> 
> > > > 考虑开题上传一次失败日志再分析一下？
> 
> > > 
> 
> > > 
> 
> > > 我最近同样出现楼主的问题，配置都正确，但是突然有次-449错误，当时没放在心上。结果后面开始出现楼主问题，我怀疑是ip上传过多“被风控”，现在就是一会好一会坏，完全看运气。不知道这个是否支持代理上传，尝试下
> 
> > 
> 
> > -449理论上已经被 #24 修复了，看commit内容应该是哔哩哔哩日常api升级引起的。尝试用最新的release了吗？风控的话可以尝试登录官方投稿工具试一下，如果需要短信那就确实要用token登录了
> 
> 
> 
> 是的，我记得刚开始就是出现-449错误，我也修改了。但是用了半个月左右就开始出现-2100，是用最新的，官方投稿工具也完全不需要短信。
> 
> 当时我记得是布置了多个计划任务上传正常的，再我额外加了一个任务之后开始全部出现问题

有可能是因为触发了验证码，我这个repo的验证码识别出了些问题，过段时间才有空去解决。换个ip地址和账号如果不能复现就可能是因为验证码

**Comment by FortuneDayssss** [comment]
短期解决方案可以使用access token方式登录，获取一次access token可以用一个月。

其实我之前已经在做其他端的api模拟以及新验证码识别了。不过做了一半其他事情有点多，暂时处于搁置状态

**Comment by xiaoxinhuozhu** [comment]
> > > > > > 亲测，用户名密码登录的方式失效了，从昨天开始
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > @qazwsdc反对一波，今天上午才用这个库成功上传了两稿多p视频（BV1BP4y1s727和BV1zf4y137dD）
> > 
> > 
> > > > > 考虑开题上传一次失败日志再分析一下？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 我最近同样出现楼主的问题，配置都正确，但是突然有次-449错误，当时没放在心上。结果后面开始出现楼主问题，我怀疑是ip上传过多“被风控”，现在就是一会好一会坏，完全看运气。不知道这个是否支持代理上传，尝试下
> > 
> > 
> > > 
> > 
> > 
> > > -449理论上已经被 #24 修复了，看commit内容应该是哔哩哔哩日常api升级引起的。尝试用最新的release了吗？风控的话可以尝试登录官方投稿工具试一下，如果需要短信那就确实要用token登录了
> > 
> > 
> > 是的，我记得刚开始就是出现-449错误，我也修改了。但是用了半个月左右就开始出现-2100，是用最新的，官方投稿工具也完全不需要短信。
> > 当时我记得是布置了多个计划任务上传正常的，再我额外加了一个任务之后开始全部出现问题
> 
> 有可能是因为触发了验证码，我这个repo的验证码识别出了些问题，过段时间才有空去解决。换个ip地址和账号如果不能复现就可能是因为验证码

感谢，我会尝试的，我这边一天次数上传的确多

**Comment by FortuneDayssss** [comment]
emmm....目前手里有个三个月以前逆的新key-secret，周末也许可以修完

**Comment by FortuneDayssss** [comment]
如果还有什么要讨论的在 #26 里讨论吧，#26 的标题清晰一些
