### ISSUE TITLE
请问封面必须由页面进行上传，不支持外部链接是什么意思呢？谢谢

### ISSUE THREAD

**Issue by syntaxist** [FortuneDayssss/BilibiliUploader#19]
{"code":21008,"message":"封面必须由页面进行上传，不支持外部链接","ttl":1}

**Comment by syntaxist** [comment]
是因为B站把封面上传接口关闭了吗？

**Comment by FortuneDayssss** [comment]
无论你是从投稿工具还是网页投稿，封面都是从本地上传的而不是使用外链。我只是模拟了这个过程。不能使用外部链接是b站的设计。

**Comment by syntaxist** [comment]
那请问大佬，我要想修改封面的话，应该怎么做呢？直接使用本地的图片地址也会得到这个提示。谢谢！！

**Comment by FortuneDayssss** [comment]
我一直用的是本地图片路径，一直都可以正常上传投稿。

建议你先检查一下你的本地图片文件路径填写的对不对

**Comment by syntaxist** [comment]
检查了，还是不是XD

if __name__ == '__main__':
            uploader = BilibiliUploader()
            uploader.login("username", "password")
        parts = []
        uploader.edit(
            bvid="BVnumber",
            parts = parts,
            title='test',
            cover='C:/Users/Kyle K/Desktop/cap.png',
            )

**Comment by FortuneDayssss** [comment]
我找到原因了，十分抱歉是个bug。我刚刚已经修复了。你可以更新到最新的代码测试一下修复情况，git pull一下或者重新clone。

**Comment by syntaxist** [comment]
太好了，谢谢！

**Comment by FortuneDayssss** [comment]
你那边跑完自己的代码的话可以在这个issue里反馈一下是否成功吗？我这边目前没有可以测试edit的稿子不太好测试
谢谢

**Comment by syntaxist** [comment]
已经跑成功了。谢谢！！

**Comment by FortuneDayssss** [comment]
感谢反馈，帮我查出一个一年都没发现的bug
