### ISSUE TITLE
登陆失败，debug了一下发现是需要过验证码的

### ISSUE THREAD

**Issue by Wszl** [FortuneDayssss/BilibiliUploader#2]
b'{"ts":1593235915,"message":"CAPTCHA is not match","code":-105}'

**Comment by Wszl** [comment]
在pc端投稿工具发现，确实需要验证码了。。。 b站动作这么快的
![image](https://user-images.githubusercontent.com/19342733/85915671-12421e80-b87c-11ea-85e0-be3c44c98f63.png)

**Comment by FortuneDayssss** [comment]
短时间内大量登录会导致针对ip的验证码…过一段时间再登录验证码就没了，目前版本还没解决验证码的问题

我在写针对验证码的神经网络…写得比较慢

**Comment by Wszl** [comment]
> 
> 
> 短时间内大量登录会导致针对ip的验证码…过一段时间再登录验证码就没了，目前版本还没解决验证码的问题
> 
> 我在写针对验证码的神经网络…写得比较慢

或许可以参考上传工具本身，将登陆信息持久化，不再每次启动时进行login

**Comment by FortuneDayssss** [comment]
> > 短时间内大量登录会导致针对ip的验证码…过一段时间再登录验证码就没了，目前版本还没解决验证码的问题
> > 我在写针对验证码的神经网络…写得比较慢
> 
> 或许可以参考上传工具本身，将登陆信息持久化，不再每次启动时进行login

嗯后面有时间我把持久化登录信息加进去吧。

**Comment by qianghuohhh** [comment]
> > > 短时间内大量登录会导致针对ip的验证码…过一段时间再登录验证码就没了，目前版本还没解决验证码的问题
> > > 我在写针对验证码的神经网络…写得比较慢
> > 
> > 
> > 或许可以参考上传工具本身，将登陆信息持久化，不再每次启动时进行login
> 
> 嗯后面有时间我把持久化登录信息加进去吧。

大佬加油

**Comment by qianghuohhh** [comment]
> > > 短时间内大量登录会导致针对ip的验证码…过一段时间再登录验证码就没了，目前版本还没解决验证码的问题
> > > 我在写针对验证码的神经网络…写得比较慢
> > 
> > 
> > 或许可以参考上传工具本身，将登陆信息持久化，不再每次启动时进行login
> 
> 嗯后面有时间我把持久化登录信息加进去吧。

大佬，验证码可以用Hsury大佬的这个，requests.post("https://bili.dev:2233/captcha", json={'image': base64.b64encode(image).decode("utf-8")})
项目地址是https://github.com/Hsury/Bilibili-Toolkit

**Comment by FortuneDayssss** [comment]
> > > > 短时间内大量登录会导致针对ip的验证码…过一段时间再登录验证码就没了，目前版本还没解决验证码的问题
> > > > 我在写针对验证码的神经网络…写得比较慢
> > > 
> > > 
> > > 或许可以参考上传工具本身，将登陆信息持久化，不再每次启动时进行login
> > 
> > 
> > 嗯后面有时间我把持久化登录信息加进去吧。
> 
> 大佬，验证码可以用Hsury大佬的这个，requests.post("https://bili.dev:2233/captcha", json={'image': base64.b64encode(image).decode("utf-8")})
> 项目地址是https://github.com/Hsury/Bilibili-Toolkit

谢谢提醒，我去试试

**Comment by Wszl** [comment]
> > > > 短时间内大量登录会导致针对ip的验证码…过一段时间再登录验证码就没了，目前版本还没解决验证码的问题
> > > > 我在写针对验证码的神经网络…写得比较慢
> > > 
> > > 
> > > 或许可以参考上传工具本身，将登陆信息持久化，不再每次启动时进行login
> > 
> > 
> > 嗯后面有时间我把持久化登录信息加进去吧。
> 
> 大佬，验证码可以用Hsury大佬的这个，requests.post("https://bili.dev:2233/captcha", json={'image': base64.b64encode(image).decode("utf-8")})
> 项目地址是https://github.com/Hsury/Bilibili-Toolkit

该项目的验证码识别是自己做的服务，https://bili.dev:2233/captcha 需要授权码的，而且滥用别人的服务还是不太好弄，期待 @FortuneDayssss 实现

**Comment by FortuneDayssss** [comment]
> > > > > 短时间内大量登录会导致针对ip的验证码…过一段时间再登录验证码就没了，目前版本还没解决验证码的问题
> > > > > 我在写针对验证码的神经网络…写得比较慢
> > > > 
> > > > 
> > > > 或许可以参考上传工具本身，将登陆信息持久化，不再每次启动时进行login
> > > 
> > > 
> > > 嗯后面有时间我把持久化登录信息加进去吧。
> > 
> > 
> > 大佬，验证码可以用Hsury大佬的这个，requests.post("https://bili.dev:2233/captcha", json={'image': base64.b64encode(image).decode("utf-8")})
> > 项目地址是https://github.com/Hsury/Bilibili-Toolkit
> 
> 该项目的验证码识别是自己做的服务，https://bili.dev:2233/captcha 需要授权码的，而且滥用别人的服务还是不太好弄，期待 @FortuneDayssss 实现

我用深度学习训练的模型目前正确率很低。。。可能验证码识别还得过一段时间才能实现，避免频繁密码登录就可以避免验证码，可以先用持久化的access token登录。（其实体感大概五分钟内小于十次登录验证码就不会出现）
一个access token的时长一般是30天，可以用refresh token来刷新时间（刷新功能目前还没写Orz，还在搬家中...以后有空把issue里提到的功能都写了）

**Comment by himself07** [comment]
加油，好项目支持

**Comment by FortuneDayssss** [comment]
#6 
验证码识别已实现
