### ISSUE TITLE
大佬，这个可以实现批量视频上传么？

### ISSUE THREAD

**Issue by peaceanddemocracy** [FortuneDayssss/BilibiliUploader#25]

**Comment by FortuneDayssss** [comment]
可以的

**Comment by peaceanddemocracy** [comment]
win版批量上传的有嘛，linux的不太方便，文件在win上

**Comment by FortuneDayssss** [comment]
你可以自己用python读文件夹然后用这个包批量上传。目前没有提供GUI的计划，因为windows直接可以用官方投稿工具。

**Comment by peaceanddemocracy** [comment]
win的官方投稿只能一个一个上传，没办法批量上传

**Comment by Yuelioi** [comment]
> win的官方投稿只能一个一个上传，没办法批量上传
我正好写了下，你可以看看
https://www.yuelili.com/multi-upload-tool/
