### ISSUE TITLE
login fail, error code = -2100

### ISSUE THREAD

**Issue by jhonprice** [FortuneDayssss/BilibiliUploader#26]
/api/v3/oauth2/login 接口返回 {'ts': 1629334284, 'code': -2100, 'message': '请升级到最新版本'}

**Comment by wpcwzy** [comment]
感觉和昨天讨论的 #17 后几条comment有关？

**Comment by jhonprice** [comment]
> 
> 
> 感觉和昨天讨论的 #17 后几条comment有关？

看起来像，我再试试

**Comment by wpcwzy** [comment]
issue个人感觉先不用关吧，昨天讨论的时候有两三个人都反映登录有问题，其中 @xiaoxinhuozhu 也提到了-2100的code，应该确实是repo本身需要更新了
后几条comment里提到的token登录也只适合应急，不提供refresh_token的话有效期只有30天

**Comment by jhonprice** [comment]
#17 暂时用着吧，目前看来换了ip，换了账号，问题依然存在，我先关了，有进展再说

**Comment by jhonprice** [comment]
目前看来换了ip，换了账号，问题依然存在

**Comment by FortuneDayssss** [comment]
> 目前看来换了ip，换了账号，问题依然存在

是的，目前看来是API更新的导致的，我周末修

**Comment by FortuneDayssss** [comment]
更新了一个登录的API暂时算是紧急修复好了，不过很不优雅有技术债。
新的API用了好多个不同的key secret对，没全逆出来（IDA苦手QAQ），得过段时间全搞定才能全面更新。

**Comment by FortuneDayssss** [comment]
已修复
