### ISSUE TITLE
我想写个GUI，如何获取上传信息

### ISSUE THREAD

**Issue by Yuelioi** [FortuneDayssss/BilibiliUploader#27]
除了改源码以外。
比如我单击上传按钮，可以实时显示上传到第几个了。目前只能在控制台显示

**Comment by FortuneDayssss** [comment]
windows投稿工具其实是有gui的。
我这个项目最初的目的是把只能走gui的东西命令行化，重写gui岂不是套娃套回去了……

**Comment by Yuelioi** [comment]
> windows投稿工具其实是有gui的。
> 我这个项目最初的目的是把只能走gui的东西命令行化，重写gui岂不是套娃套回去了……

啊。。因为有人有需求批量上传，所以我想写个工具。现在B站网页多P上传只对部分人可用，客户端只能一个一个选，没法多选。

**Comment by FortuneDayssss** [comment]
嗯嗯你有这个需求想做的话我支持你(・ω・)ノ

b站的上传接口是一个一个chunk传的，你可以稍微看下core.py里面的逻辑，upload chunk是上传一块，你可以用块数来做进度条追踪

**Comment by Yuelioi** [comment]
> 嗯嗯你有这个需求想做的话我支持你(・ω・)ノ
> 
> b站的上传接口是一个一个chunk传的，你可以稍微看下core.py里面的逻辑，upload chunk是上传一块，你可以用块数来做进度条追踪

谢谢大佬回复~
