### ISSUE TITLE
请问怎么设置biliuploader不通过代理上传？

### ISSUE THREAD

**Issue by wpcwzy** [FortuneDayssss/BilibiliUploader#28]
因为某些特殊需求服务器需要一直挂全局代理，但是全局代理下用bilibiliuploader登录时会出现无法解析域名的报错，关闭全局代理即可恢复正常。
请问是否考虑增加参数 来设置是否通过代理上传，或者修改哪些代码片段能达到这些效果？
打扰了！

**Comment by FortuneDayssss** [comment]
linux console的http&https代理是从环境变量设置的，
也许可以通过类似如下的方式
http_proxy=”” && https_proxy=”” && python3 xxx.py
来进行单条指令的变量覆盖来关全局代理

**Comment by wpcwzy** [comment]
> linux console的http&https代理是从环境变量设置的，
> 也许可以通过类似如下的方式
> http_proxy=”” && https_proxy=”” && python3 xxx.py
> 来进行单条指令的变量覆盖来关全局代理

感谢！
