### ISSUE TITLE
膜拜大佬！能否实现给已有视频增加新P的功能？

### ISSUE THREAD

**Issue by qazwsdc** [FortuneDayssss/BilibiliUploader#3]
比如已经有了一个视频，想在这基础上增加新的part视频。。。跪求

**Comment by FortuneDayssss** [comment]
不错的想法~
过一小段时间我把几个新功能一块写了吧= =；

**Comment by qazwsdc** [comment]
跪谢大佬

**Comment by FortuneDayssss** [comment]
最新的commit已经实现了一个简易的投稿修改功能，提供av号和修改的内容即可，可以追加多个视频并且选择追加分p位置。暂时没做删除分p的功能。
