### ISSUE TITLE
多次尝试后确认，登录接口失效

### ISSUE THREAD

**Issue by myishh** [FortuneDayssss/BilibiliUploader#32]
尝试了多个账号，更换IP也不行，全部提示下面的信息
{'code': 86066, 'message': '该账号冻结中', 'ttl': 1, 'data': None}

**Comment by FortuneDayssss** [comment]
我这里复现了，可能是B站API更新了。。预估下周末修QAQ

**Comment by myishh** [comment]
> 我这里复现了，可能是B站API更新了。。预估下周末修QAQ

好的 期待尽快修复 ヾ(◍°∇°◍)ﾉﾞ

**Comment by LinusLing** [comment]
保持关注

**Comment by xnfa** [comment]
很有意思的发现，回滚到 c7f00ac94c2092ae67b9b1984024ce2c44e1eacb 登陆接口就可用了。

**Comment by myishh** [comment]
> 很有意思的发现，回滚到 [c7f00ac](https://github.com/FortuneDayssss/BilibiliUploader/commit/c7f00ac94c2092ae67b9b1984024ce2c44e1eacb) 登陆接口就可用了。
我这边回滚后提示是：
{'ts': 1635850973, 'code': -2100, 'message': '请升级到最新版本'}

**Comment by jhonprice** [comment]
(′д｀ )

**Comment by FortuneDayssss** [comment]
(๑•̀ㅂ•́)و✧ 周末逆完了，刚刚验证完了，这一两天封装完代码就push

**Comment by joyspce** [comment]
谢谢

**Comment by FortuneDayssss** [comment]
已修复
新登录api异地登录会有短信验证码，如果遇到，需要手动验证过后即可使用

**Comment by myishh** [comment]
> 已修复 新登录api异地登录会有短信验证码，如果遇到，需要手动验证过后即可使用

测试成功  感谢~
