### ISSUE TITLE
登录显示验证码错误

### ISSUE THREAD

**Issue by ZhengYitong2333** [FortuneDayssss/BilibiliUploader#33]
response{'code': -105, 'data': {'cookie_info': None, 'message': '', 'sso': None, 'status': 0, 'token_info': None, 'url': 'f'}, 'message': '验证码错误', 'ttl': 1}

**Comment by FortuneDayssss** [comment]
目前不支持新验证码的自动识别，请换个ip或者过24小时再试，或者使用access token登录
