### ISSUE TITLE
上传报错"No file in body."

### ISSUE THREAD

**Issue by esrrhs** [FortuneDayssss/BilibiliUploader#38]
upload XXXXX added in pool
chunk0/133
filename: XXXXX.mp4
408
b'{"OK":-1,"info":"No file in body."}'
chunk0/133
filename: XXXXX.mp4
408
b'{"OK":-1,"info":"No file in body."}'
chunk0/133
filename: XXXXX.mp4
408
b'{"OK":-1,"info":"No file in body."}'
chunk0/133
filename: XXXXX.mp4
408
b'{"OK":-1,"info":"No file in body."}'
chunk0/133
filename: XXXXX.mp4
408
b'{"OK":-1,"info":"No file in body."}'
video part XXXXX finished, status: False
upload failed

**Comment by esrrhs** [comment]
哦，是我的问题

**Comment by wanghaisiyue** [comment]
> 哦，是我的问题

请问怎么处理的，我也遇到了，两台电脑，一台可以，一台一直这个错

**Comment by wanghaisiyue** [comment]
请问是怎么处理的？我也遇到这个问题，两台电脑一台可以，一台一直不行，除了文件路径，别的没有区别

**Comment by wanghaisiyue** [comment]
> 哦，是我的问题

请问是怎么处理的？我也遇到这个问题，两台电脑一台可以，一台一直不行，除了文件路径，别的没有区别

**Comment by wanghaisiyue** [comment]
> > 哦，是我的问题
> 
> 请问是怎么处理的？我也遇到这个问题，两台电脑一台可以，一台一直不行，除了文件路径，别的没有区别

我也解决了，依赖的包版本低，记录下

**Comment by esrrhs** [comment]
> 
> 
> > > 哦，是我的问题
> > 
> > 
> > 请问是怎么处理的？我也遇到这个问题，两台电脑一台可以，一台一直不行，除了文件路径，别的没有区别
> 
> 我也解决了，依赖的包版本低，记录下

是吗？是哪个包？我发现只要是中文文件名就不行，必须是英文的

**Comment by wanghaisiyue** [comment]
> 



> > > > 哦，是我的问题
> > > 
> > > 
> > > 请问是怎么处理的？我也遇到这个问题，两台电脑一台可以，一台一直不行，除了文件路径，别的没有区别
> > 
> > 
> > 我也解决了，依赖的包版本低，记录下
> 
> 是吗？是哪个包？我发现只要是中文文件名就不行，必须是英文的

我是升级了涉及到的所有的，上传的文件名都是中文的，没有影响

**Comment by esrrhs** [comment]
> > 
> 
> > > > > 哦，是我的问题
> > > > 
> > > > 
> > > > 请问是怎么处理的？我也遇到这个问题，两台电脑一台可以，一台一直不行，除了文件路径，别的没有区别
> > > 
> > > 
> > > 我也解决了，依赖的包版本低，记录下
> > 
> > 
> > 是吗？是哪个包？我发现只要是中文文件名就不行，必须是英文的
> 
> 我是升级了涉及到的所有的，上传的文件名都是中文的，没有影响

咋升级的？求方法

**Comment by wanghaisiyue** [comment]
> > > 
> > 
> > 
> > > > > > 哦，是我的问题
> > > > > 
> > > > > 
> > > > > 请问是怎么处理的？我也遇到这个问题，两台电脑一台可以，一台一直不行，除了文件路径，别的没有区别
> > > > 
> > > > 
> > > > 我也解决了，依赖的包版本低，记录下
> > > 
> > > 
> > > 是吗？是哪个包？我发现只要是中文文件名就不行，必须是英文的
> > 
> > 
> > 我是升级了涉及到的所有的，上传的文件名都是中文的，没有影响
> 
> 咋升级的？求方法

pip install --upgrade，包就是requirements.txt里的，你看看现在的版本是不是符合要求了

**Comment by esrrhs** [comment]
> > > > 
> > > 
> > > 
> > > > > > > 哦，是我的问题
> > > > > > 
> > > > > > 
> > > > > > 请问是怎么处理的？我也遇到这个问题，两台电脑一台可以，一台一直不行，除了文件路径，别的没有区别
> > > > > 
> > > > > 
> > > > > 我也解决了，依赖的包版本低，记录下
> > > > 
> > > > 
> > > > 是吗？是哪个包？我发现只要是中文文件名就不行，必须是英文的
> > > 
> > > 
> > > 我是升级了涉及到的所有的，上传的文件名都是中文的，没有影响
> > 
> > 
> > 咋升级的？求方法
> 
> pip install --upgrade，包就是requirements.txt里的，你看看现在的版本是不是符合要求了

可以了，感谢老哥
